image: docker:20

stages:
  - build

variables:
  BUILD_IMAGE_NAME: "chaos/dotnet-nukebuild"

build:
  stage: build
  tags:
    - linux
    - docker
  only:
    - tags
  script:
    - export
    - docker version
    - docker login -u ${CI_DOCKER_LOGIN} -p ${CI_DOCKER_TOKEN}
    - docker build -t ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker tag ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG} ${BUILD_IMAGE_NAME}:latest
    - docker push ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push ${BUILD_IMAGE_NAME}:latest
