image: docker:20

stages:
  - build

variables:
  BUILD_IMAGE_NAME: "chaos/dotnet-nukebuild"
  DOCKER_PUSHRM_URL: "https://github.com/christian-korneck/docker-pushrm/releases/download/v1.8.0/docker-pushrm_linux_amd64"

build:
  stage: build
  tags:
    - linux
    - docker
  only:
    - tags
  script:
    - export
    - docker version
    - mkdir -p ~/.docker/cli-plugins
    - wget -o ~/.docker/cli-plugins/docker-pushrm ${DOCKER_PUSHRM_URL}
    - chmod +x ~/.docker/cli-plugins/docker-pushrm
    - docker login -u ${CI_DOCKER_LOGIN} -p ${CI_DOCKER_TOKEN}
    - docker build -t ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker tag ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG} ${BUILD_IMAGE_NAME}:latest
    - docker push ${BUILD_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker push ${BUILD_IMAGE_NAME}:latest
    - docker pushrm ${BUILD_IMAGE_NAME}
